[project]
name = "llm-custom-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mlx>=0.27.1",
    "pydantic>=2.11.7",
    "sentencepiece>=0.2.0",
]
